### ISSUE TITLE
Monterey

### ISSUE THREAD

**Issue by Bombadaa** [FallenChromium/Acer-Swift3-2018-hackintosh#8]
Hi, will you update Monterey support 7.4. soon ?

**Comment by FallenChromium** [comment]
I don't think I will do it soon, because I don't own this laptop anymore, but I have an identical one at work. Feel free to make a PR, as far as I understand no breaking changes were made, we just need to update OpenCore (and upgrade its' config), and also update kexts to their latest versions. That said, I will do it myself if nobody will send a PR by the end of this year, so, yeah... :D

**Comment by Thiadeth** [comment]
Hey, I have the same laptop SF315-51-520J from 2018, opencore 7.8.  got it to run on Monterey.  Can you explain what all your SSDTS do? and what is the bootstrap foler?   When i used dortanias guide it worked and ran but when i used your ssdts and kext i get stuck at loading installation information under the monterey installer for a solid 20 minutes and then again at 1 hour 18 minutes remaining. I also found that XOSI breaks my windows boot.   

VoodoI2CSynaptics also not working, had to disable advanced mode to get my trackpad to work. used usb mouse cause it was horrible

**Comment by FallenChromium** [comment]
I've updated the config with my patches to fully support Monterey. If you have any other questions, please ask in a separate issue so that it will be easier for others to find :)

@Thiadeth,
Regarding the Windows boot - I did not do any of my patches with consideration of Windows because I do not use it and thus I can't test it, so it may have been a problem. I've updated several SSDTs (took them from another repo), so this issue could be resolved now, if it persists, open another thread

On the matter of trackpad - my method relies on VoodooI2C's Windows Precision protocol, not synaptics protocol (because it is inferior). For any help on the trackpad side, contact VoodooI2C's team on Gitter or GitHub (and of course, read all the official docs). You can leave your IOReg report and DSDT dump here, so that I could see what's your exact trackpad model and how it can be accomodated into my patch, but I can't guarantee anything, because it looks like you have different hardware. Either way, try the latest release and see what'll happen
